version: '3.8'

services:
  api-1:
    build:
      context: .
      dockerfile: BankingDemo.API/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__Default=Host=db;Port=5432;Database=bankingdemodb;Username=admin;Password=zxcvasdfwqer
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
        
  api-2:
    build:
      context: .
      dockerfile: BankingDemo.API/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ConnectionStrings__Default=Host=db;Port=5432;Database=bankingdemodb;Username=admin;Password=zxcvasdfwqer
      - ASPNETCORE_ENVIRONMENT=Development 
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=zxcvasdfwqer
      - POSTGRES_DB=bankingdemodb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bankingdemodb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: